
common_utils_packages:
  - curl
  - git
  - htop
  - jq
  - net-tools
  - tar
  - tmux
  - traceroute
  - tree
  - unzip
  - vim
  - wget

debian_utils_packages:
  - build-essential
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - python3-venv
  - tk-dev
  - uuid-dev
  - zlib1g-dev

redhat_utils_packages:
  - "@Development Tools"
  - bzip2-devel
  - epel-release
  - libffi-devel
  - libuuid-devel
  - ncurses-devel
  - openssl-devel
  - readline-devel
  - sqlite-devel
  - tk-devel
  - xz-devel
  - zlib-devel
