---
- name: Touch hushlogin file
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  become: false

- name: Setup vim configuration and dotfiles
  import_tasks: vim.yml
  become: false

- name: Setup tmux configuration
  import_tasks: tmux.yml
  become: false

- name: Copy bash_functions and aliasses
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  loop:
    - "bash_functions"
    - "bash_aliasses"
  become: false

- name: Configure git settings
  import_tasks: git.yml
  become: false

- name: Append user settings to bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ lookup('file', 'bashrc') }}"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter : EOF
  become: false

