## start numbering windows/panes at 1
set -g base-index 1
setw -g pane-base-index 1

## position status bar at top
set-option -g status-position top

## renumber after one is closed
set-option -g renumber-windows on

## set mouse support on
setw -g mouse on

## set 256 colors
set -g default-terminal "screen-256color"

## set the pane border colors
set -g pane-border-style 'fg=colour235,bg=colour238'
set -g pane-active-border-style 'fg=colour51,bg=colour236'

## allow easier navigation with ctrl arrow keys
set-window-option -g xterm-keys on

## use vi copy mode
setw -g mode-keys vi

## gruvbox theme
set -g @tmux-gruvbox 'dark'

## Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'andrewjstryker/tmux-airline'

run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tpm/tmux-gruvbox'
run '~/.tmux/plugins/tpm/tmux-airline'
