devtools_user: "{{ ansible_user_id }}"
devtools_home: "/home/{{ devtools_user }}"

software_dir: "{{ devtools_home }}/software/ansible-managed"
local_bin_dir: "{{ devtools_home }}/.local/bin"

aws_cli_version: "2.31.2"
aws_session_manager_plugin_version: "latest"
ccat_version: "1.1.0"
eza_version: "v0.23.4"
golang_version: "1.26.2"
gopls_version: "latest"
helm_version: "v4.1.4"
k9s_version: "v0.50.18"
kind_version: "v0.31.0"
kubectl_version: "v1.36.0"
nvim_version: "0.12.2"
poetry_version: "2.3.4"
pyenv_version: "v2.6.27"
terraform_version: "1.14.9"
uv_version: "0.11.7"
vim_version: "9.2.0398"