---
- name: Verify {{ tool_name }} binaries exist
  stat:
    path: "{{ software_dir }}/{{ tool_name }}/{{ item.src }}"
  register: binary_stat
  loop: "{{ binary_symlinks }}"
  failed_when: not binary_stat.stat.exists
  loop_control:
    label: "{{ item.dest }}"

- name: Symlink {{ tool_name }} binaries
  file:
    src: "{{ software_dir }}/{{ tool_name }}/{{ item.src }}"
    dest: "{{ local_bin_dir }}/{{ item.dest }}"
    state: link
    force: true
  loop: "{{ binary_symlinks }}"
  changed_when: false