---
- name: Download eza artifacts
  import_tasks: _download_artifact.yml
  vars:
    tool_name: eza
    artifact_version: "{{ eza_version }}"
    artifact_type: archive
    artifact_url: "https://github.com/eza-community/eza/releases/download/{{ eza_version }}/eza_x86_64-unknown-linux-gnu.tar.gz"
    artifact_creates: eza

- name: Symlink eza binaries
  import_tasks: _symlink_binaries.yml
  vars:
    tool_name: eza
    binary_symlinks:
      - src: eza
        dest: eza